
class Weaknesses(object):

    def __init__(self):

        self.nor = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 1,
                    "gra": 1,
                    "ice": 1,
                    "fig": 2,
                    "poi": 1,
                    "gro": 1,
                    "fly": 1,
                    "psy": 1,
                    "bug": 1,
                    "roc": 1,
                    "gho": 0,
                    "dra": 1,
                    "dar": 1,
                    "ste": 1,
                    "fai": 1}

        self.fir = {"nor": 1,
                    "fir": 0.5,
                    "wat": 2,
                    "ele": 1,
                    "gra": 0.5,
                    "ice": 0.5,
                    "fig": 1,
                    "poi": 1,
                    "gro": 2,
                    "fly": 1,
                    "psy": 1,
                    "bug": 0.5,
                    "roc": 2,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 0.5,
                    "fai": 0.5}

        self.wat = {"nor": 1,
                    "fir": 0.5,
                    "wat": 0.5,
                    "ele": 2,
                    "gra": 2,
                    "ice": 0.5,
                    "fig": 1,
                    "poi": 1,
                    "gro": 1,
                    "fly": 1,
                    "psy": 1,
                    "bug": 1,
                    "roc": 1,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 0.5,
                    "fai": 1}

        self.ele = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 0.5,
                    "gra": 1,
                    "ice": 1,
                    "fig": 1,
                    "poi": 1,
                    "gro": 2,
                    "fly": 0.5,
                    "psy": 1,
                    "bug": 1,
                    "roc": 1,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 0.5,
                    "fai": 1}

        self.gra = {"nor": 1,
                    "fir": 2,
                    "wat": 0.5,
                    "ele": 0.5,
                    "gra": 0.5,
                    "ice": 2,
                    "fig": 1,
                    "poi": 2,
                    "gro": 0.5,
                    "fly": 2,
                    "psy": 1,
                    "bug": 2,
                    "roc": 1,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 1,
                    "fai": 1}

        self.ice = {"nor": 1,
                    "fir": 2,
                    "wat": 1,
                    "ele": 1,
                    "gra": 1,
                    "ice": 0.5,
                    "fig": 2,
                    "poi": 1,
                    "gro": 1,
                    "fly": 1,
                    "psy": 1,
                    "bug": 1,
                    "roc": 2,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 2,
                    "fai": 1}

        self.fig = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 1,
                    "gra": 1,
                    "ice": 1,
                    "fig": 1,
                    "poi": 1,
                    "gro": 1,
                    "fly": 2,
                    "psy": 2,
                    "bug": 0.5,
                    "roc": 0.5,
                    "gho": 1,
                    "dra": 1,
                    "dar": 0.5,
                    "ste": 1,
                    "fai": 2}

        self.poi = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 1,
                    "gra": 0.5,
                    "ice": 1,
                    "fig": 0.5,
                    "poi": 0.5,
                    "gro": 2,
                    "fly": 1,
                    "psy": 2,
                    "bug": 0.5,
                    "roc": 1,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 1,
                    "fai": 0.5}

        self.gro = {"nor": 1,
                    "fir": 1,
                    "wat": 2,
                    "ele": 0,
                    "gra": 2,
                    "ice": 2,
                    "fig": 1,
                    "poi": 0.5,
                    "gro": 1,
                    "fly": 1,
                    "psy": 1,
                    "bug": 1,
                    "roc": 0.5,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 1,
                    "fai": 1}

        self.fly = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 2,
                    "gra": 0.5,
                    "ice": 2,
                    "fig": 0.5,
                    "poi": 1,
                    "gro": 0,
                    "fly": 1,
                    "psy": 1,
                    "bug": 0.5,
                    "roc": 2,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 1,
                    "fai": 1}

        self.psy = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 1,
                    "gra": 1,
                    "ice": 1,
                    "fig": 0.5,
                    "poi": 1,
                    "gro": 1,
                    "fly": 1,
                    "psy": 0.5,
                    "bug": 2,
                    "roc": 1,
                    "gho": 2,
                    "dra": 1,
                    "dar": 2,
                    "ste": 1,
                    "fai": 1}

        self.bug = {"nor": 1,
                    "fir": 2,
                    "wat": 1,
                    "ele": 1,
                    "gra": 0.5,
                    "ice": 1,
                    "fig": 0.5,
                    "poi": 1,
                    "gro": 0.5,
                    "fly": 2,
                    "psy": 1,
                    "bug": 1,
                    "roc": 2,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 1,
                    "fai": 1}

        self.roc = {"nor": 0.5,
                    "fir": 0.5,
                    "wat": 2,
                    "ele": 1,
                    "gra": 2,
                    "ice": 1,
                    "fig": 2,
                    "poi": 0.5,
                    "gro": 2,
                    "fly": 0.5,
                    "psy": 1,
                    "bug": 1,
                    "roc": 1,
                    "gho": 1,
                    "dra": 1,
                    "dar": 1,
                    "ste": 2,
                    "fai": 1}

        self.gho = {"nor": 0,
                    "fir": 1,
                    "wat": 1,
                    "ele": 1,
                    "gra": 1,
                    "ice": 1,
                    "fig": 0,
                    "poi": 0.5,
                    "gro": 1,
                    "fly": 1,
                    "psy": 1,
                    "bug": 0.5,
                    "roc": 1,
                    "gho": 2,
                    "dra": 1,
                    "dar": 2,
                    "ste": 1,
                    "fai": 1}

        self.dra = {"nor": 1,
                    "fir": 0.5,
                    "wat": 0.5,
                    "ele": 0.5,
                    "gra": 0.5,
                    "ice": 2,
                    "fig": 1,
                    "poi": 1,
                    "gro": 1,
                    "fly": 1,
                    "psy": 1,
                    "bug": 1,
                    "roc": 1,
                    "gho": 1,
                    "dra": 2,
                    "dar": 1,
                    "ste": 1,
                    "fai": 2}

        self.dar = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 1,
                    "gra": 1,
                    "ice": 1,
                    "fig": 2,
                    "poi": 1,
                    "gro": 1,
                    "fly": 1,
                    "psy": 0,
                    "bug": 2,
                    "roc": 1,
                    "gho": 0.5,
                    "dra": 1,
                    "dar": 0.5,
                    "ste": 1,
                    "fai": 2}

        self.ste = {"nor": 0.5,
                    "fir": 2,
                    "wat": 1,
                    "ele": 1,
                    "gra": 0.5,
                    "ice": 0.5,
                    "fig": 2,
                    "poi": 0,
                    "gro": 2,
                    "fly": 0.5,
                    "psy": 0.5,
                    "bug": 0.5,
                    "roc": 0.5,
                    "gho": 1,
                    "dra": 0.5,
                    "dar": 1,
                    "ste": 0.5,
                    "fai": 0.5}

        self.fai = {"nor": 1,
                    "fir": 1,
                    "wat": 1,
                    "ele": 1,
                    "gra": 1,
                    "ice": 1,
                    "fig": 0.5,
                    "poi": 2,
                    "gro": 1,
                    "fly": 1,
                    "psy": 1,
                    "bug": 0.5,
                    "roc": 1,
                    "gho": 1,
                    "dra": 0,
                    "dar": 0.5,
                    "ste": 2,
                    "fai": 1}

        self.type_list = {"nor": self.nor, "fir": self.fir, "wat": self.wat,
                          "ele": self.ele, "gra": self.gra, "ice": self.ice,
                          "fig": self.fig, "poi": self.poi, "gro": self.gro,
                          "fly": self.fly, "psy": self.psy, "bug": self.bug,
                          "roc": self.roc, "gho": self.gho, "dra": self.dra,
                          "dar": self.dar, "ste": self.ste, "fai": self.fai}


class Strengths(object):
    def __init__(self):
        self.nor = {'bug': 1,
                    'dar': 1,
                    'dra': 1,
                    'ele': 1,
                    'fai': 1,
                    'fig': 1,
                    'fir': 1,
                    'fly': 1,
                    'gho': 0,
                    'gra': 1,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 0.5,
                    'ste': 0.5,
                    'wat': 1}

        self.fir = {'bug': 2,
                    'dar': 1,
                    'dra': 0.5,
                    'ele': 1,
                    'fai': 1,
                    'fig': 1,
                    'fir': 0.5,
                    'fly': 1,
                    'gho': 1,
                    'gra': 2,
                    'gro': 1,
                    'ice': 2,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 0.5,
                    'ste': 2,
                    'wat': 0.5}

        self.wat = {'bug': 1,
                    'dar': 1,
                    'dra': 0.5,
                    'ele': 1,
                    'fai': 1,
                    'fig': 1,
                    'fir': 2,
                    'fly': 1,
                    'gho': 1,
                    'gra': 0.5,
                    'gro': 2,
                    'ice': 1,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 2,
                    'ste': 1,
                    'wat': 0.5}

        self.ele = {'bug': 1,
                    'dar': 1,
                    'dra': 0.5,
                    'ele': 0.5,
                    'fai': 1,
                    'fig': 1,
                    'fir': 1,
                    'fly': 2,
                    'gho': 1,
                    'gra': 0.5,
                    'gro': 0,
                    'ice': 1,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 1,
                    'ste': 1,
                    'wat': 2}

        self.gra = {'bug': 0.5,
                    'dar': 1,
                    'dra': 0.5,
                    'ele': 1,
                    'fai': 1,
                    'fig': 1,
                    'fir': 0.5,
                    'fly': 0.5,
                    'gho': 1,
                    'gra': 0.5,
                    'gro': 2,
                    'ice': 1,
                    'nor': 1,
                    'poi': 0.5,
                    'psy': 1,
                    'roc': 2,
                    'ste': 0.5,
                    'wat': 2}

        self.ice = {'bug': 1,
                    'dar': 1,
                    'dra': 2,
                    'ele': 1,
                    'fai': 1,
                    'fig': 1,
                    'fir': 0.5,
                    'fly': 2,
                    'gho': 1,
                    'gra': 2,
                    'gro': 2,
                    'ice': 0.5,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 1,
                    'ste': 0.5,
                    'wat': 0.5}

        self.fig = {'bug': 0.5,
                    'dar': 2,
                    'dra': 1,
                    'ele': 1,
                    'fai': 0.5,
                    'fig': 1,
                    'fir': 1,
                    'fly': 0.5,
                    'gho': 0,
                    'gra': 1,
                    'gro': 1,
                    'ice': 2,
                    'nor': 2,
                    'poi': 0.5,
                    'psy': 0.5,
                    'roc': 2,
                    'ste': 2,
                    'wat': 1}

        self.poi = {'bug': 1,
                    'dar': 1,
                    'dra': 1,
                    'ele': 1,
                    'fai': 2,
                    'fig': 1,
                    'fir': 1,
                    'fly': 1,
                    'gho': 0.5,
                    'gra': 2,
                    'gro': 0.5,
                    'ice': 1,
                    'nor': 1,
                    'poi': 0.5,
                    'psy': 1,
                    'roc': 0.5,
                    'ste': 0,
                    'wat': 1}

        self.gro = {'bug': 0.5,
                    'dar': 1,
                    'dra': 1,
                    'ele': 2,
                    'fai': 1,
                    'fig': 1,
                    'fir': 2,
                    'fly': 0,
                    'gho': 1,
                    'gra': 0.5,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 2,
                    'psy': 1,
                    'roc': 2,
                    'ste': 2,
                    'wat': 1}

        self.fly = {'bug': 2,
                    'dar': 1,
                    'dra': 1,
                    'ele': 0.5,
                    'fai': 1,
                    'fig': 2,
                    'fir': 1,
                    'fly': 1,
                    'gho': 1,
                    'gra': 2,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 0.5,
                    'ste': 0.5,
                    'wat': 1}

        self.psy = {'bug': 1,
                    'dar': 0,
                    'dra': 1,
                    'ele': 1,
                    'fai': 1,
                    'fig': 2,
                    'fir': 1,
                    'fly': 1,
                    'gho': 1,
                    'gra': 1,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 2,
                    'psy': 0.5,
                    'roc': 1,
                    'ste': 0.5,
                    'wat': 1}

        self.bug = {'bug': 1,
                    'dar': 2,
                    'dra': 1,
                    'ele': 1,
                    'fai': 0.5,
                    'fig': 0.5,
                    'fir': 0.5,
                    'fly': 0.5,
                    'gho': 0.5,
                    'gra': 2,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 0.5,
                    'psy': 2,
                    'roc': 1,
                    'ste': 0.5,
                    'wat': 1}

        self.roc = {'bug': 2,
                    'dar': 1,
                    'dra': 1,
                    'ele': 1,
                    'fai': 1,
                    'fig': 0.5,
                    'fir': 2,
                    'fly': 2,
                    'gho': 1,
                    'gra': 1,
                    'gro': 0.5,
                    'ice': 2,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 1,
                    'ste': 0.5,
                    'wat': 1}

        self.gho = {'bug': 1,
                    'dar': 0.5,
                    'dra': 1,
                    'ele': 1,
                    'fai': 1,
                    'fig': 1,
                    'fir': 1,
                    'fly': 1,
                    'gho': 2,
                    'gra': 1,
                    'gro': 1,
                    'ice': 1,
                    'nor': 0,
                    'poi': 1,
                    'psy': 2,
                    'roc': 1,
                    'ste': 1,
                    'wat': 1}

        self.dra = {'bug': 1,
                    'dar': 1,
                    'dra': 2,
                    'ele': 1,
                    'fai': 0,
                    'fig': 1,
                    'fir': 1,
                    'fly': 1,
                    'gho': 1,
                    'gra': 1,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 1,
                    'ste': 0.5,
                    'wat': 1}

        self.dar = {'bug': 1,
                    'dar': 0.5,
                    'dra': 1,
                    'ele': 1,
                    'fai': 0.5,
                    'fig': 0.5,
                    'fir': 1,
                    'fly': 1,
                    'gho': 2,
                    'gra': 1,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 1,
                    'psy': 2,
                    'roc': 1,
                    'ste': 1,
                    'wat': 1}

        self.ste = {'bug': 1,
                    'dar': 1,
                    'dra': 1,
                    'ele': 0.5,
                    'fai': 2,
                    'fig': 1,
                    'fir': 0.5,
                    'fly': 1,
                    'gho': 1,
                    'gra': 1,
                    'gro': 1,
                    'ice': 2,
                    'nor': 1,
                    'poi': 1,
                    'psy': 1,
                    'roc': 2,
                    'ste': 0.5,
                    'wat': 0.5}

        self.fai = {'bug': 1,
                    'dar': 2,
                    'dra': 2,
                    'ele': 1,
                    'fai': 1,
                    'fig': 2,
                    'fir': 0.5,
                    'fly': 1,
                    'gho': 1,
                    'gra': 1,
                    'gro': 1,
                    'ice': 1,
                    'nor': 1,
                    'poi': 0.5,
                    'psy': 1,
                    'roc': 1,
                    'ste': 0.5,
                    'wat': 1}

        self.type_list = {"nor": self.nor, "fir": self.fir, "wat": self.wat,
                          "ele": self.ele, "gra": self.gra, "ice": self.ice,
                          "fig": self.fig, "poi": self.poi, "gro": self.gro,
                          "fly": self.fly, "psy": self.psy, "bug": self.bug,
                          "roc": self.roc, "gho": self.gho, "dra": self.dra,
                          "dar": self.dar, "ste": self.ste, "fai": self.fai}

